language: perl

perl:
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

install:
    - cpanm Dancer Mock::Quick Crypt::SaltedHash YAML --quiet --notest

script:
    - perl Makefile.PL
    - make test
